[project]
name = "py-noodle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "c-two>=0.2.4",
    "fastapi>=0.116.1",
    "pyyaml>=6.0.2",
    "pyzmq>=27.0.0",
]
